version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env

volumes:
  mydatabase:
