version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      - CERTBOT_EMAIL=armanmoztar@outlook.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./user_conf.d:/etc/nginx/user_conf.d
      - ./certs:/etc/letsencrypt
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:
